-- WhatsApp + automation schema
-- Safe to re-run.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS wa_conversations (
    id                   bigint generated by default as identity PRIMARY KEY,
    created_at           timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at           timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    phone_number         text NOT NULL,
    display_name         text,
    last_message_preview text,
    last_message_at      timestamptz,
    unread_count         integer DEFAULT 0 NOT NULL,
    provider             text DEFAULT 'baileys' NOT NULL,
    session_name         text DEFAULT 'primary' NOT NULL,
    metadata             jsonb DEFAULT '{}'::jsonb NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_wa_conversations_phone
    ON wa_conversations (phone_number);

DROP TRIGGER IF EXISTS set_wa_conversations_updated_at ON wa_conversations;
CREATE TRIGGER set_wa_conversations_updated_at
BEFORE UPDATE ON wa_conversations
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE wa_conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow wa conversations all" ON wa_conversations;
CREATE POLICY "Allow wa conversations all"
    ON wa_conversations FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


CREATE TABLE IF NOT EXISTS wa_templates (
    id           bigint generated by default as identity PRIMARY KEY,
    created_at   timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at   timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    name         text NOT NULL,
    category     text DEFAULT 'general' NOT NULL,
    message_type text DEFAULT 'text' NOT NULL,
    body_text    text DEFAULT '' NOT NULL,
    variables    jsonb DEFAULT '[]'::jsonb NOT NULL,
    asset_id     bigint,
    media_url    text,
    mime_type    text,
    file_name    text,
    caption      text DEFAULT '' NOT NULL,
    is_active    boolean DEFAULT true NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_wa_templates_name
    ON wa_templates (name);

DROP TRIGGER IF EXISTS set_wa_templates_updated_at ON wa_templates;
CREATE TRIGGER set_wa_templates_updated_at
BEFORE UPDATE ON wa_templates
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE wa_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow wa templates all" ON wa_templates;
CREATE POLICY "Allow wa templates all"
    ON wa_templates FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


CREATE TABLE IF NOT EXISTS message_assets (
    id          bigint generated by default as identity PRIMARY KEY,
    created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    name        text NOT NULL,
    bucket      text DEFAULT 'message-assets' NOT NULL,
    path        text NOT NULL,
    public_url  text NOT NULL,
    mime_type   text,
    size_bytes  bigint,
    metadata    jsonb DEFAULT '{}'::jsonb NOT NULL
);

ALTER TABLE message_assets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow message assets all" ON message_assets;
CREATE POLICY "Allow message assets all"
    ON message_assets FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


CREATE TABLE IF NOT EXISTS automation_jobs (
    id                     bigint generated by default as identity PRIMARY KEY,
    created_at             timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at             timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    channel                text NOT NULL,
    trigger_event          text,
    phone_number           text,
    caller_name            text,
    template_name          text,
    message_type           text DEFAULT 'text' NOT NULL,
    body_text              text DEFAULT '' NOT NULL,
    caption                text DEFAULT '' NOT NULL,
    media_url              text,
    mime_type              text,
    file_name              text,
    asset_id               bigint,
    related_call_room_id   text,
    related_call_log_id    bigint,
    related_appointment_id bigint,
    scheduled_for          timestamptz NOT NULL,
    status                 text DEFAULT 'pending' NOT NULL,
    retry_count            integer DEFAULT 0 NOT NULL,
    max_retries            integer DEFAULT 3 NOT NULL,
    last_error             text,
    idempotency_key        text NOT NULL,
    payload                jsonb DEFAULT '{}'::jsonb NOT NULL,
    provider_message_id    text,
    dispatch_id            text,
    CONSTRAINT automation_jobs_channel_check CHECK (channel IN ('whatsapp', 'call')),
    CONSTRAINT automation_jobs_status_check CHECK (
        status IN ('pending', 'retry', 'processing', 'sent', 'failed', 'cancelled', 'pending_review', 'launched')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_automation_jobs_idempotency
    ON automation_jobs (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_automation_jobs_schedule_status
    ON automation_jobs (status, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_automation_jobs_phone
    ON automation_jobs (phone_number);
CREATE INDEX IF NOT EXISTS idx_automation_jobs_appointment
    ON automation_jobs (related_appointment_id);

DROP TRIGGER IF EXISTS set_automation_jobs_updated_at ON automation_jobs;
CREATE TRIGGER set_automation_jobs_updated_at
BEFORE UPDATE ON automation_jobs
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE automation_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow automation jobs all" ON automation_jobs;
CREATE POLICY "Allow automation jobs all"
    ON automation_jobs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


CREATE TABLE IF NOT EXISTS wa_messages (
    id                     bigint generated by default as identity PRIMARY KEY,
    created_at             timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    conversation_id        bigint REFERENCES wa_conversations(id) ON DELETE SET NULL,
    phone_number           text NOT NULL,
    direction              text NOT NULL,
    status                 text DEFAULT 'queued' NOT NULL,
    message_type           text DEFAULT 'text' NOT NULL,
    template_name          text,
    body_text              text DEFAULT '' NOT NULL,
    caption                text DEFAULT '' NOT NULL,
    media_url              text,
    mime_type              text,
    file_name              text,
    asset_id               bigint,
    provider               text DEFAULT 'baileys' NOT NULL,
    provider_message_id    text,
    error_text             text,
    related_appointment_id bigint,
    related_job_id         bigint REFERENCES automation_jobs(id) ON DELETE SET NULL,
    metadata               jsonb DEFAULT '{}'::jsonb NOT NULL,
    sent_at                timestamptz,
    delivered_at           timestamptz,
    read_at                timestamptz,
    CONSTRAINT wa_messages_direction_check CHECK (direction IN ('inbound', 'outbound')),
    CONSTRAINT wa_messages_type_check CHECK (message_type IN ('text', 'image', 'document', 'audio'))
);

CREATE INDEX IF NOT EXISTS idx_wa_messages_phone
    ON wa_messages (phone_number, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_wa_messages_provider_message
    ON wa_messages (provider_message_id)
    WHERE provider_message_id IS NOT NULL;

ALTER TABLE wa_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow wa messages all" ON wa_messages;
CREATE POLICY "Allow wa messages all"
    ON wa_messages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


INSERT INTO storage.buckets (id, name, public)
VALUES ('message-assets', 'message-assets', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public read message assets" ON storage.objects;
CREATE POLICY "Public read message assets"
    ON storage.objects
    FOR SELECT
    USING (bucket_id = 'message-assets');

DROP POLICY IF EXISTS "Allow message assets upload" ON storage.objects;
CREATE POLICY "Allow message assets upload"
    ON storage.objects
    FOR INSERT TO anon, authenticated
    WITH CHECK (bucket_id = 'message-assets');


INSERT INTO wa_templates (name, category, message_type, body_text, variables, caption, is_active)
VALUES
    ('booking_confirmed', 'booking', 'text', 'Hi {caller_name}, your appointment is confirmed for {booking_date} at {booking_time}. Booking ID: {booking_id}.', '["caller_name", "booking_date", "booking_time", "booking_id"]'::jsonb, '', true),
    ('booking_reminder_24h', 'booking', 'text', 'Reminder: your appointment is tomorrow at {booking_time} on {booking_date}. Reply here if you need help.', '["booking_date", "booking_time"]'::jsonb, '', true),
    ('booking_reminder_2h', 'booking', 'text', 'Reminder: your appointment is in around 2 hours at {booking_time} today.', '["booking_time"]'::jsonb, '', true),
    ('booking_cancelled', 'booking', 'text', 'Hi {caller_name}, your appointment for {booking_date} at {booking_time} has been cancelled. If you want to reschedule, just reply here.', '["caller_name", "booking_date", "booking_time"]'::jsonb, '', true),
    ('no_booking_followup_2h', 'followup', 'text', 'Hi {caller_name}, thanks for taking the call earlier. If you want to continue, reply here and we can help with the next step.', '["caller_name"]'::jsonb, '', true),
    ('no_booking_followup_next_day', 'followup', 'text', 'Hi {caller_name}, following up from yesterday''s call. If you want to book or ask anything, just message here.', '["caller_name"]'::jsonb, '', true),
    ('manual_brochure', 'manual', 'text', 'Hi {caller_name}, sharing the details we discussed. Let us know if you want the team to call back.', '["caller_name"]'::jsonb, '', true),
    ('manual_document_share', 'manual', 'document', 'Hi {caller_name}, sharing the requested document here.', '["caller_name"]'::jsonb, 'Requested document for {caller_name}', true)
ON CONFLICT (name) DO UPDATE SET
    category = EXCLUDED.category,
    message_type = EXCLUDED.message_type,
    body_text = EXCLUDED.body_text,
    variables = EXCLUDED.variables,
    caption = EXCLUDED.caption,
    is_active = EXCLUDED.is_active,
    updated_at = timezone('utc', now());
