-- ══════════════════════════════════════════════════════════════════════════════
-- SUPABASE MIGRATION v3 — Internal appointments planner
-- Safe to re-run.
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS appointments (
    id              bigint generated by default as identity PRIMARY KEY,
    created_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    title           text        NOT NULL DEFAULT 'Site Visit',
    contact_name    text,
    contact_phone   text,
    scheduled_start timestamptz NOT NULL,
    scheduled_end   timestamptz NOT NULL,
    timezone        text        NOT NULL DEFAULT 'Asia/Kolkata',
    status          text        NOT NULL DEFAULT 'scheduled',
    notes           text,
    source          text        NOT NULL DEFAULT 'manual_ui',
    CONSTRAINT appointments_valid_status CHECK (status IN ('scheduled', 'cancelled', 'completed')),
    CONSTRAINT appointments_valid_source CHECK (source IN ('voice_agent', 'manual_ui')),
    CONSTRAINT appointments_valid_window CHECK (scheduled_end > scheduled_start)
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_appointments_updated_at ON appointments;
CREATE TRIGGER set_appointments_updated_at
BEFORE UPDATE ON appointments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE appointments
    DROP CONSTRAINT IF EXISTS appointments_no_overlap;

ALTER TABLE appointments
    ADD CONSTRAINT appointments_no_overlap
    EXCLUDE USING gist (
        tstzrange(scheduled_start, scheduled_end, '[)') WITH &&
    )
    WHERE (status = 'scheduled');

CREATE INDEX IF NOT EXISTS idx_appointments_scheduled_start
    ON appointments (scheduled_start);

CREATE INDEX IF NOT EXISTS idx_appointments_status
    ON appointments (status);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow internal appointment select" ON appointments;
CREATE POLICY "Allow internal appointment select"
    ON appointments FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow internal appointment insert" ON appointments;
CREATE POLICY "Allow internal appointment insert"
    ON appointments FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow internal appointment update" ON appointments;
CREATE POLICY "Allow internal appointment update"
    ON appointments FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow internal appointment delete" ON appointments;
CREATE POLICY "Allow internal appointment delete"
    ON appointments FOR DELETE TO anon, authenticated USING (true);

-- ══════════════════════════════════════════════════════════════════════════════
-- DONE. Run this in Supabase SQL Editor after migration_v2.sql.
-- ══════════════════════════════════════════════════════════════════════════════
