-- WhatsApp inbox metadata + voice turn metrics
-- Safe to re-run.

ALTER TABLE wa_conversations
    ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false NOT NULL,
    ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false NOT NULL,
    ADD COLUMN IF NOT EXISTS last_read_at timestamptz;

ALTER TABLE call_logs
    ADD COLUMN IF NOT EXISTS call_room_id text;

CREATE INDEX IF NOT EXISTS idx_call_logs_phone_number
    ON call_logs (phone_number);

CREATE INDEX IF NOT EXISTS idx_call_logs_call_room_id
    ON call_logs (call_room_id);

CREATE TABLE IF NOT EXISTS call_turn_metrics (
    id                 bigint generated by default as identity PRIMARY KEY,
    created_at         timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    call_room_id       text,
    phone_number       text,
    turn_index         integer NOT NULL DEFAULT 0,
    speaker            text NOT NULL DEFAULT 'assistant',
    stt_endpoint_ms    numeric,
    kb_ms              numeric,
    llm_first_token_ms numeric,
    tts_first_audio_ms numeric,
    tool_ms            numeric,
    total_turn_ms      numeric,
    kb_used            boolean DEFAULT false NOT NULL,
    kb_skipped_reason  text,
    metadata           jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT call_turn_metrics_speaker_check CHECK (speaker IN ('assistant', 'system'))
);

CREATE INDEX IF NOT EXISTS idx_call_turn_metrics_room_turn
    ON call_turn_metrics (call_room_id, turn_index);

CREATE INDEX IF NOT EXISTS idx_call_turn_metrics_phone_created
    ON call_turn_metrics (phone_number, created_at);

ALTER TABLE call_turn_metrics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow call turn metrics all" ON call_turn_metrics;
CREATE POLICY "Allow call turn metrics all"
    ON call_turn_metrics FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
