-- ══════════════════════════════════════════════════════════════════════════════
-- SUPABASE BASE SETUP — Run first on a fresh project
-- Safe to re-run.
-- ══════════════════════════════════════════════════════════════════════════════

-- ── CALL LOGS ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS call_logs (
    id               bigint generated by default as identity primary key,
    created_at       timestamptz default timezone('utc', now()) not null,
    phone_number     text,
    caller_name      text,
    duration_seconds integer,
    transcript       text,
    summary          text,
    recording_url    text
);

ALTER TABLE call_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all actions for service role" ON call_logs;
CREATE POLICY "Enable all actions for service role"
    ON call_logs
    FOR ALL
    USING (true)
    WITH CHECK (true);


-- ── APPOINTMENTS ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS appointments (
    id              bigint generated by default as identity primary key,
    created_at      timestamptz default timezone('utc', now()) not null,
    updated_at      timestamptz default timezone('utc', now()) not null,
    title           text        not null default 'Site Visit',
    contact_name    text,
    contact_phone   text,
    scheduled_start timestamptz not null,
    scheduled_end   timestamptz not null,
    timezone        text        not null default 'Asia/Kolkata',
    status          text        not null default 'scheduled',
    notes           text,
    source          text        not null default 'manual_ui',
    CONSTRAINT appointments_valid_status CHECK (status IN ('scheduled', 'cancelled', 'completed')),
    CONSTRAINT appointments_valid_source CHECK (source IN ('voice_agent', 'manual_ui')),
    CONSTRAINT appointments_valid_window CHECK (scheduled_end > scheduled_start)
);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow internal appointment select" ON appointments;
CREATE POLICY "Allow internal appointment select"
    ON appointments FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow internal appointment insert" ON appointments;
CREATE POLICY "Allow internal appointment insert"
    ON appointments FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow internal appointment update" ON appointments;
CREATE POLICY "Allow internal appointment update"
    ON appointments FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow internal appointment delete" ON appointments;
CREATE POLICY "Allow internal appointment delete"
    ON appointments FOR DELETE TO anon, authenticated USING (true);


-- ── STORAGE — Call recordings ───────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('call-recordings', 'call-recordings', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public read recordings" ON storage.objects;
CREATE POLICY "Public read recordings"
    ON storage.objects
    FOR SELECT
    USING (bucket_id = 'call-recordings');

DROP POLICY IF EXISTS "Service role write recordings" ON storage.objects;
CREATE POLICY "Service role write recordings"
    ON storage.objects
    FOR INSERT
    WITH CHECK (bucket_id = 'call-recordings');
